---
- name: Include variables
  include_vars: "vars/{{ ansible_distribution }}.yml"
  tags: always

- name: Import install tasks
  import_tasks: "install_{{ ansible_distribution }}.yml"
  tags:
  - nginx
  - install_nginx

- name: Import configure tasks
  import_tasks: "configure_{{ ansible_distribution }}.yml"
  tags:
  - nginx
  - configure_nginx