---
- name: Include variables
  include_vars: "vars/{{ ansible_distribution }}.yml"
  tags: always

- name: Include install tasks
  include_tasks: "install_{{ ansible_distribution }}.yml"
  tags:
  - nginx
  - install_nginx

- name: Include configure tasks
  include_tasks: "configure_{{ ansible_distribution }}.yml"
  tags:
  - nginx
  - configure_nginx